## Numpy Part I
**Numpy** is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

[This document](http://cs231n.github.io/python-numpy-tutorial/)

### ARRAYS
A numpy array **numpy.ndarray** is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [15]:
import numpy as np

a = np.array([1, 2, 3, 4])   # Create a rank 1 array
print(f'type={type(a)} shape={a.shape} a[2]={a[2]}')            # Prints "<class 'numpy.ndarray'>"
a[0] = 5   # Change an element of the array
print(f'array changed to {a}')

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b, 'b shape:', b.shape, ', [0,0] [0,1] [1,1] =',b[0, 0], b[0, 1], b[1, 1])   # Prints "1 2 5"

type=<class 'numpy.ndarray'> shape=(4,) a[2]=3
array changed to [5 2 3 4]
[[1 2 3]
 [4 5 6]] b shape: (2, 3) , [0,0] [0,1] [1,1] = 1 2 5


### ZEROS ONES FULL EYE RANDOM
Numpy also provides many functions to create arrays:

In [3]:
import numpy as np

print("random array\n",np.random.random((2,2))*100) 

random array
 [[17.54326565 89.51814842]
 [ 6.59973781 47.3876206 ]]


In [3]:
import numpy as np

print("all zeros\n",np.zeros((2,2)))
print("all 1s array\n",np.ones((4,2)))
print("constant array\n",np.full((2,2), 7))

all zeros
 [[0. 0.]
 [0. 0.]]
all 1s array
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
constant array
 [[7 7]
 [7 7]]


In [2]:
print("identity matrix\n", np.eye(3))  # Create a 3x3 identity matrix
print("random array\n",np.random.random((2,2)))  # Create an array filled with random values

identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random array
 [[0.33836678 0.50868481]
 [0.50812727 0.56746153]]


You can read about other methods of array creation in the [documentation](http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).


### ARRAY INDEXING
Numpy offers several ways to index into arrays.

#### Slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #  rank 2 array with shape (3, 4)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
2
77


#### Mix integer indexing with slice indexing
Doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [6]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape, type(row_r1))  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape, type(row_r2))  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,) <class 'numpy.ndarray'>
[[5 6 7 8]] (1, 4) <class 'numpy.ndarray'>


In [7]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a[0, 0], a[1, 1], a[2, 0])
print(a[[0, 1, 2], [0, 1, 0]]) # return a (3,) array
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) ## equivalent to above 

# When using integer array indexing, you can reuse the same element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]


#### 3-D Array

In [36]:
a = np.random.random((3,4,2))*100
print(a)
print('a[[0,1],[0,1],[0,1]] =',a[[0,1],[0,1],[0,1]])
print('a[[0,1],[0,1]] =',a[[0,1],[0,1]])

[[[33.33374647 27.80437734]
  [36.91751616 81.61515512]
  [41.11728846  7.19644641]
  [21.73148505 52.00446574]]

 [[44.03664344  1.78243789]
  [16.22787234 84.07855837]
  [43.65927296 25.97998646]
  [59.10431125 97.90453299]]

 [[35.30427557 12.26823006]
  [57.94289189 41.29955597]
  [47.87578418 32.92268663]
  [47.57675338 93.93946305]]]
a[[0,1],[0,1],[0,1]] = [33.33374647 84.07855837]
a[[0,1],[0,1]] = [[33.33374647 27.80437734]
 [16.22787234 84.07855837]]


In [39]:
print('a[[0]] =',a[[0]])
print('a[0] =',a[0])
print('a[0,1] =',a[0,1])

a[[0]] = [[[33.33374647 27.80437734]
  [36.91751616 81.61515512]
  [41.11728846  7.19644641]
  [21.73148505 52.00446574]]]
a[0] = [[33.33374647 27.80437734]
 [36.91751616 81.61515512]
 [41.11728846  7.19644641]
 [21.73148505 52.00446574]]
a[0,1] = [36.91751616 81.61515512]


One useful trick with integer array indexing is **selecting or mutating one element from each row** of a matrix using arrange()

In [41]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a.shape)

# Create an array of indices
b = np.array([0, 2, 0, 1])

print('np.arange(4):',np.arange(4)) # n : number of rows
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

(4, 3)
np.arange(4): [0 1 2 3]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [15]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a % 2 == 0)
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array consisting
# of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[[False  True]
 [False  True]
 [False  True]]
[2 4 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Numpy Aggregate Functions

In [1]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print("Mean: ", np.mean(array1))
print("Std: ", np.std(array1)) 
print("Var: ", np.var(array1))
print("Sum: ", np.sum(array1))
print("Prod: ", np.prod(array1))

Mean:  35.0
Std:  17.07825127659933
Var:  291.6666666666667
Sum:  210
Prod:  720000000
