# Indexing

On [Kaggle](https://www.kaggle.com/residentmario/indexing-selecting-assigning)

Both **loc** and **iloc** are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second. **loc is label-based** while **iloc is integer index based**.

In [2]:
import numpy as np
import pandas as pd

arr = np.random.randn(4, 3) * 10
df = pd.DataFrame(arr)
df2 = pd.DataFrame(arr,columns=list('ABC'))
print(arr)
print(df)
print(df.loc[2,1], df.iloc[2,1], df2.loc[2,'B'], df2.iloc[2,1], arr[2,1])

[[ -2.81120723  -0.06305835  -2.81444496]
 [ -7.09379997  10.51234753 -14.71334479]
 [ -1.6019546    3.07748953 -26.38754516]
 [  0.43201541   0.18367542  21.78134764]]
          0          1          2
0 -2.811207  -0.063058  -2.814445
1 -7.093800  10.512348 -14.713345
2 -1.601955   3.077490 -26.387545
3  0.432015   0.183675  21.781348
3.0774895309379207 3.0774895309379207 3.0774895309379207 3.0774895309379207 3.0774895309379207


In [18]:
print('\narr[2,]', type(arr[2,]))
print(arr[2,])

print('\ndf.loc[2,1]',type(df.loc[2,1]),df.loc[2,1]) # numpy.float64, 2 integer index returns the cell 
print('\ndf.loc[2,]',type(df.loc[2,])) # Series, integer index n in first plce returns n-th row
print(df.loc[2,])

print('\ndf.loc[:,1]',type(df.loc[:,1])) # Series, ':' in first place and integer index n in second plce returns n-th column
print(df.loc[:,1])

print('\ndf.loc[:,:1]',type(df.loc[:,:1])) # DataFrame, both first and second are ranges or list
print(df.loc[:,:1])

print("\ndf2.loc[:,['A','B']]",type(df2.loc[:,['A','B']])) # DataFrame, both first and second are ranges or list
print(df2.loc[:,['A','B']])


arr[2,] <class 'numpy.ndarray'>
[13.65014957 -6.43849941 -1.52890047]

df.loc[2,1] <class 'numpy.float64'> -6.438499408073266

df.loc[2,] <class 'pandas.core.series.Series'>
0    13.650150
1    -6.438499
2    -1.528900
Name: 2, dtype: float64

df.loc[:,1] <class 'pandas.core.series.Series'>
0    8.693577
1   -0.327727
2   -6.438499
3    7.577255
Name: 1, dtype: float64

df.loc[:,:1] <class 'pandas.core.frame.DataFrame'>
           0         1
0  -5.400252  8.693577
1   5.427399 -0.327727
2  13.650150 -6.438499
3  -1.113487  7.577255

df2.loc[:,['A','B']] <class 'pandas.core.frame.DataFrame'>
           A         B
0  -5.400252  8.693577
1   5.427399 -0.327727
2  13.650150 -6.438499
3  -1.113487  7.577255


**Data conversion**: float + numpy.float64 -> numpy.float64

In [19]:
t = 3 + df.iloc[2,1]
s = 3 + float(df.iloc[2,1])
print(type(t),t, type(s),s)

<class 'numpy.float64'> -3.438499408073266 <class 'float'> -3.438499408073266


### read_csv
Start with **head()**, to decide whetehr index is in the csv, add **index_col** parameter as needed. Then use **shape, dtypes and describe()** to have a better picture of the dataframe.

In [20]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)

In [21]:
reviews.head(3)

country                                        description   designation  \
0     Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco   
1  Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos   
2        US  Tart and snappy, the flavors of lime flesh and...           NaN   

   points  price           province           region_1           region_2  \
0      87    NaN  Sicily & Sardinia               Etna                NaN   
1      87   15.0              Douro                NaN                NaN   
2      87   14.0             Oregon  Willamette Valley  Willamette Valley   

     taster_name taster_twitter_handle  \
0  Kerin O’Keefe          @kerinokeefe   
1     Roger Voss            @vossroger   
2   Paul Gregutt           @paulgwine    

                                           title         variety  \
0              Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1  Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2  Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   

                winery  
0              Nicosia  
1  Quinta dos Avidagos  
2            Rainstorm

In [22]:
print(reviews.shape)
print(reviews.dtypes)
reviews.describe()

(129971, 13)
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object


points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [23]:
reviews.loc[:5, ['taster_name', 'taster_twitter_handle', 'points']]

taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
2        Paul Gregutt           @paulgwine       87
3  Alexander Peartree                   NaN      87
4        Paul Gregutt           @paulgwine       87
5   Michael Schachner           @wineschach      87

### Stock Prices

In [32]:
ibm = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=IBM&apikey=demo&datatype=csv',index_col=0)
ibm

open    high       low   close  adjusted_close    volume  \
timestamp                                                                
2021-01-22  120.70  120.70  117.3600  118.61      118.610000  38063533   
2021-01-21  130.12  132.24  130.0500  131.65      131.650000  12819233   
2021-01-20  129.70  131.06  128.5600  130.08      130.080000   5598705   
2021-01-19  129.28  129.59  128.0885  129.02      129.020000   5397956   
2021-01-15  128.28  129.24  127.6700  128.39      128.390000   4905506   
...            ...     ...       ...     ...             ...       ...   
2020-09-04  124.35  125.35  121.2400  122.30      120.598489   6018238   
2020-09-03  128.19  129.95  123.6500  124.45      122.718577   5716750   
2020-09-02  123.72  128.70  123.5750  128.18      126.396683   6592430   
2020-09-01  122.85  123.95  122.1500  123.40      121.683185   3155623   
2020-08-31  125.25  125.25  123.0300  123.31      121.594438   4827879   

            dividend_amount  split_coefficient  
timestamp                                       
2021-01-22              0.0                1.0  
2021-01-21              0.0                1.0  
2021-01-20              0.0                1.0  
2021-01-19              0.0                1.0  
2021-01-15              0.0                1.0  
...                     ...                ...  
2020-09-04              0.0                1.0  
2020-09-03              0.0                1.0  
2020-09-02              0.0                1.0  
2020-09-01              0.0                1.0  
2020-08-31              0.0                1.0  

[100 rows x 8 columns]

### Iteration throught Dataframe

Try NOT to use, use **Windows functions** instead

In [35]:
for index, row in ibm[:10].iterrows():
    print(row["open"], row["volume"])

120.7 38063533.0
130.12 12819233.0
129.7 5598705.0
129.28 5397956.0
128.28 4905506.0
128.02 7503180.0
129.15 7677739.0
129.09 3729068.0
127.95 5602466.0
128.57 4676487.0


### Window functions

- shift(n)
- expanding()
- rolling(n)

https://towardsdatascience.com/window-functions-in-pandas-eaece0421f7

In [15]:
stock_df = pd.DataFrame([100, 98, 95, 96, 99, 102, 103, 105, 105, 108], columns=['price'])
print(stock_df)
stock_df['prev_price'] = stock_df.shift(1)
print(stock_df)

   price
0    100
1     98
2     95
3     96
4     99
5    102
6    103
7    105
8    105
9    108
   price  prev_price
0    100         NaN
1     98       100.0
2     95        98.0
3     96        95.0
4     99        96.0
5    102        99.0
6    103       102.0
7    105       103.0
8    105       105.0
9    108       105.0


In [16]:
stock_df['daily_return'] = stock_df['price']/stock_df['prev_price']-1
stock_df['expand_mean']=stock_df['daily_return'].expanding().mean()
stock_df['roll_mean_3']=stock_df['daily_return'].rolling(3).mean()
stock_df

price  prev_price  daily_return  expand_mean  roll_mean_3
0    100         NaN           NaN          NaN          NaN
1     98       100.0     -0.020000    -0.020000          NaN
2     95        98.0     -0.030612    -0.025306          NaN
3     96        95.0      0.010526    -0.013362    -0.013362
4     99        96.0      0.031250    -0.002209     0.003721
5    102        99.0      0.030303     0.004293     0.024026
6    103       102.0      0.009804     0.005212     0.023786
7    105       103.0      0.019417     0.007241     0.019841
8    105       105.0      0.000000     0.006336     0.009740
9    108       105.0      0.028571     0.008807     0.015996

In [17]:
stock_df['balance']=0
stock_df.loc[0,'balance']=10000

In [18]:
stock_df

price  prev_price  daily_return  expand_mean  roll_mean_3  balance
0    100         NaN           NaN          NaN          NaN    10000
1     98       100.0     -0.020000    -0.020000          NaN        0
2     95        98.0     -0.030612    -0.025306          NaN        0
3     96        95.0      0.010526    -0.013362    -0.013362        0
4     99        96.0      0.031250    -0.002209     0.003721        0
5    102        99.0      0.030303     0.004293     0.024026        0
6    103       102.0      0.009804     0.005212     0.023786        0
7    105       103.0      0.019417     0.007241     0.019841        0
8    105       105.0      0.000000     0.006336     0.009740        0
9    108       105.0      0.028571     0.008807     0.015996        0